 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.thepetproject.swing.pages;

import com.mycompany.thepetproject.utils.pages.PageController;

/**
 *
 * @author lilac
 */
public class Authentication extends javax.swing.JPanel {
    private PageController pageController;

    /**
     * Creates new form Authentication
     */
    public Authentication() {
        initComponents();
        this.pageController = PageController.getInstance();
        tabbedAuthPage.setSelectedIndex(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tabbedAuthPage = new javax.swing.JTabbedPane();
        panelSignUp = new javax.swing.JPanel();
        panelSignUpCard = new javax.swing.JPanel();
        labelSignUp1 = new javax.swing.JLabel();
        labelUsername2 = new javax.swing.JLabel();
        labelPassword2 = new javax.swing.JLabel();
        labelAdmin1 = new javax.swing.JLabel();
        labelOrLoginAs1 = new javax.swing.JLabel();
        textFieldUsername2 = new javax.swing.JTextField();
        textFieldPassword2 = new javax.swing.JTextField();
        labelAlreadyHave = new javax.swing.JLabel();
        labelLogin1 = new javax.swing.JLabel();
        textFieldConfirmPassword = new javax.swing.JTextField();
        signUpBackBtn = new javax.swing.JButton();
        panelRound2 = new com.mycompany.thepetproject.swing.components.PanelRound();
        labelLoginAdmin3 = new javax.swing.JLabel();
        panelLogin = new javax.swing.JPanel();
        panelLoginCard1 = new javax.swing.JPanel();
        textFieldUsername1 = new javax.swing.JTextField();
        textFieldPassword1 = new javax.swing.JTextField();
        labelDontHave = new javax.swing.JLabel();
        labelSignUp = new javax.swing.JLabel();
        labelLogin = new javax.swing.JLabel();
        labelUsername1 = new javax.swing.JLabel();
        labelPassword1 = new javax.swing.JLabel();
        labelAdmin = new javax.swing.JLabel();
        labelOrLoginAs = new javax.swing.JLabel();
        loginBackBtn = new javax.swing.JButton();
        panelRound1 = new com.mycompany.thepetproject.swing.components.PanelRound();
        labelLoginAdmin1 = new javax.swing.JLabel();
        panelAdmin = new javax.swing.JPanel();
        panelLoginCard = new javax.swing.JPanel();
        textFieldPassword = new javax.swing.JTextField();
        labelUserSignUp = new javax.swing.JLabel();
        labelWelcome = new javax.swing.JLabel();
        labelUsername = new javax.swing.JLabel();
        labelPassword = new javax.swing.JLabel();
        labelUserLogin = new javax.swing.JLabel();
        labelOrGoBack = new javax.swing.JLabel();
        adminBackBtn = new javax.swing.JButton();
        labelLoginButton = new javax.swing.JLabel();
        panelLoginAdmin = new com.mycompany.thepetproject.swing.components.PanelRound();
        labelLoginAdmin = new javax.swing.JLabel();
        textFieldUsername = new javax.swing.JTextField();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabbedAuthPage.setMaximumSize(new java.awt.Dimension(1000, 710));
        tabbedAuthPage.setMinimumSize(new java.awt.Dimension(1000, 710));
        tabbedAuthPage.setPreferredSize(new java.awt.Dimension(1100, 710));

        panelSignUp.setBackground(new java.awt.Color(226, 71, 42));
        panelSignUp.setMaximumSize(new java.awt.Dimension(1000, 710));
        panelSignUp.setMinimumSize(new java.awt.Dimension(1000, 710));

        panelSignUpCard.setBackground(new java.awt.Color(251, 245, 222));
        panelSignUpCard.setMaximumSize(new java.awt.Dimension(361, 426));
        panelSignUpCard.setMinimumSize(new java.awt.Dimension(361, 426));
        panelSignUpCard.setPreferredSize(new java.awt.Dimension(361, 426));

        labelSignUp1.setBackground(new java.awt.Color(251, 245, 222));
        labelSignUp1.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        labelSignUp1.setForeground(new java.awt.Color(38, 50, 56));
        labelSignUp1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSignUp1.setText("Sign Up");
        labelSignUp1.setPreferredSize(new java.awt.Dimension(130, 58));

        labelUsername2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelUsername2.setForeground(new java.awt.Color(38, 50, 56));
        labelUsername2.setText("Username");
        labelUsername2.setPreferredSize(new java.awt.Dimension(68, 17));

        labelPassword2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelPassword2.setForeground(new java.awt.Color(38, 50, 56));
        labelPassword2.setText("Password");
        labelPassword2.setPreferredSize(new java.awt.Dimension(68, 17));

        labelAdmin1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelAdmin1.setForeground(new java.awt.Color(226, 70, 43));
        labelAdmin1.setText("Admin");
        labelAdmin1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAdmin1MouseClicked(evt);
            }
        });

        labelOrLoginAs1.setForeground(new java.awt.Color(38, 50, 56));
        labelOrLoginAs1.setText("Or Login as");

        textFieldUsername2.setBackground(new java.awt.Color(255, 255, 255));
        textFieldUsername2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textFieldUsername2.setForeground(new java.awt.Color(38, 50, 56));
        textFieldUsername2.setText("Enter username");
        textFieldUsername2.setAutoscrolls(false);
        textFieldUsername2.setPreferredSize(new java.awt.Dimension(297, 37));
        textFieldUsername2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldUsername2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textFieldUsername2FocusLost(evt);
            }
        });
        textFieldUsername2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textFieldUsername2MouseClicked(evt);
            }
        });
        textFieldUsername2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldUsername2ActionPerformed(evt);
            }
        });

        textFieldPassword2.setBackground(new java.awt.Color(255, 255, 255));
        textFieldPassword2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textFieldPassword2.setForeground(new java.awt.Color(38, 50, 56));
        textFieldPassword2.setText("Enter password");
        textFieldPassword2.setPreferredSize(new java.awt.Dimension(297, 37));
        textFieldPassword2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textFieldPassword2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                textFieldPassword2MouseEntered(evt);
            }
        });

        labelAlreadyHave.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelAlreadyHave.setForeground(new java.awt.Color(38, 50, 56));
        labelAlreadyHave.setText("Already have an account?");

        labelLogin1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelLogin1.setForeground(new java.awt.Color(226, 70, 43));
        labelLogin1.setText("Login");
        labelLogin1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelLogin1MouseClicked(evt);
            }
        });

        textFieldConfirmPassword.setBackground(new java.awt.Color(255, 255, 255));
        textFieldConfirmPassword.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textFieldConfirmPassword.setForeground(new java.awt.Color(38, 50, 56));
        textFieldConfirmPassword.setText("Confirm password");
        textFieldConfirmPassword.setPreferredSize(new java.awt.Dimension(297, 37));
        textFieldConfirmPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textFieldConfirmPasswordMouseClicked(evt);
            }
        });
        textFieldConfirmPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldConfirmPasswordActionPerformed(evt);
            }
        });

        signUpBackBtn.setText("Back");
        signUpBackBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signUpBackBtnMouseClicked(evt);
            }
        });

        panelRound2.setBackground(java.awt.Color.black);
        panelRound2.setForeground(java.awt.Color.black);
        panelRound2.setRoundBottomLeft(20);
        panelRound2.setRoundBottomRight(20);
        panelRound2.setRoundTopLeft(20);
        panelRound2.setRoundTopRight(20);

        labelLoginAdmin3.setBackground(java.awt.Color.white);
        labelLoginAdmin3.setForeground(java.awt.Color.white);
        labelLoginAdmin3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLoginAdmin3.setText("Sign Up");
        labelLoginAdmin3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelLoginAdmin3, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelLoginAdmin3, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelSignUpCardLayout = new javax.swing.GroupLayout(panelSignUpCard);
        panelSignUpCard.setLayout(panelSignUpCardLayout);
        panelSignUpCardLayout.setHorizontalGroup(
            panelSignUpCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSignUpCardLayout.createSequentialGroup()
                .addGroup(panelSignUpCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSignUpCardLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(panelSignUpCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelSignUpCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(textFieldPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(textFieldUsername2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelUsername2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(panelSignUpCardLayout.createSequentialGroup()
                                    .addGap(32, 32, 32)
                                    .addGroup(panelSignUpCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelSignUpCardLayout.createSequentialGroup()
                                            .addComponent(labelOrLoginAs1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(labelAdmin1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panelSignUpCardLayout.createSequentialGroup()
                                            .addComponent(labelAlreadyHave)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(labelLogin1))))
                                .addComponent(textFieldConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelSignUp1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelSignUpCardLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(signUpBackBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSignUpCardLayout.setVerticalGroup(
            panelSignUpCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSignUpCardLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(signUpBackBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelSignUp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelUsername2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(textFieldUsername2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSignUpCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAlreadyHave)
                    .addComponent(labelLogin1))
                .addGroup(panelSignUpCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelOrLoginAs1)
                    .addComponent(labelAdmin1))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout panelSignUpLayout = new javax.swing.GroupLayout(panelSignUp);
        panelSignUp.setLayout(panelSignUpLayout);
        panelSignUpLayout.setHorizontalGroup(
            panelSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSignUpLayout.createSequentialGroup()
                .addGap(332, 332, 332)
                .addComponent(panelSignUpCard, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(429, Short.MAX_VALUE))
        );
        panelSignUpLayout.setVerticalGroup(
            panelSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSignUpLayout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(panelSignUpCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        tabbedAuthPage.addTab("tab3", panelSignUp);

        panelLogin.setBackground(new java.awt.Color(226, 71, 42));

        panelLoginCard1.setBackground(new java.awt.Color(251, 245, 222));
        panelLoginCard1.setMaximumSize(new java.awt.Dimension(361, 426));
        panelLoginCard1.setMinimumSize(new java.awt.Dimension(361, 426));
        panelLoginCard1.setName(""); // NOI18N
        panelLoginCard1.setPreferredSize(new java.awt.Dimension(361, 426));

        textFieldUsername1.setBackground(new java.awt.Color(255, 255, 255));
        textFieldUsername1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textFieldUsername1.setForeground(new java.awt.Color(38, 50, 56));
        textFieldUsername1.setText("Enter username");
        textFieldUsername1.setAutoscrolls(false);
        textFieldUsername1.setPreferredSize(new java.awt.Dimension(297, 37));
        textFieldUsername1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textFieldUsername1MouseClicked(evt);
            }
        });
        textFieldUsername1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldUsername1ActionPerformed(evt);
            }
        });

        textFieldPassword1.setBackground(new java.awt.Color(255, 255, 255));
        textFieldPassword1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textFieldPassword1.setForeground(new java.awt.Color(38, 50, 56));
        textFieldPassword1.setText("Enter password");
        textFieldPassword1.setPreferredSize(new java.awt.Dimension(297, 37));
        textFieldPassword1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textFieldPassword1MouseClicked(evt);
            }
        });

        labelDontHave.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelDontHave.setForeground(new java.awt.Color(38, 50, 56));
        labelDontHave.setText("Don't have an account? ");

        labelSignUp.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelSignUp.setForeground(new java.awt.Color(226, 70, 43));
        labelSignUp.setText("Sign Up");
        labelSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelSignUpMouseClicked(evt);
            }
        });

        labelLogin.setBackground(new java.awt.Color(251, 245, 222));
        labelLogin.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        labelLogin.setForeground(new java.awt.Color(38, 50, 56));
        labelLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLogin.setText("Login");
        labelLogin.setPreferredSize(new java.awt.Dimension(130, 58));

        labelUsername1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelUsername1.setForeground(new java.awt.Color(38, 50, 56));
        labelUsername1.setText("Username");
        labelUsername1.setPreferredSize(new java.awt.Dimension(68, 17));

        labelPassword1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelPassword1.setForeground(new java.awt.Color(38, 50, 56));
        labelPassword1.setText("Password");
        labelPassword1.setPreferredSize(new java.awt.Dimension(68, 17));

        labelAdmin.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelAdmin.setForeground(new java.awt.Color(226, 70, 43));
        labelAdmin.setText("Admin");
        labelAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelAdminMouseClicked(evt);
            }
        });

        labelOrLoginAs.setForeground(new java.awt.Color(38, 50, 56));
        labelOrLoginAs.setText("Or Login as");

        loginBackBtn.setText("Back");
        loginBackBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginBackBtnMouseClicked(evt);
            }
        });

        panelRound1.setBackground(java.awt.Color.black);
        panelRound1.setForeground(java.awt.Color.black);
        panelRound1.setRoundBottomLeft(20);
        panelRound1.setRoundBottomRight(20);
        panelRound1.setRoundTopLeft(20);
        panelRound1.setRoundTopRight(20);

        labelLoginAdmin1.setBackground(java.awt.Color.white);
        labelLoginAdmin1.setForeground(java.awt.Color.white);
        labelLoginAdmin1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLoginAdmin1.setText("Login");
        labelLoginAdmin1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelLoginAdmin1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelLoginAdmin1, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelLoginCard1Layout = new javax.swing.GroupLayout(panelLoginCard1);
        panelLoginCard1.setLayout(panelLoginCard1Layout);
        panelLoginCard1Layout.setHorizontalGroup(
            panelLoginCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(panelLoginCard1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(loginBackBtn))
            .addGroup(panelLoginCard1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(panelLoginCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelLoginCard1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(panelLoginCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLoginCard1Layout.createSequentialGroup()
                                .addComponent(labelOrLoginAs)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelLoginCard1Layout.createSequentialGroup()
                                .addComponent(labelDontHave, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelSignUp))))))
        );
        panelLoginCard1Layout.setVerticalGroup(
            panelLoginCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginCard1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(loginBackBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(textFieldUsername1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLoginCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDontHave)
                    .addComponent(labelSignUp))
                .addGroup(panelLoginCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelOrLoginAs)
                    .addComponent(labelAdmin))
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
        panelLogin.setLayout(panelLoginLayout);
        panelLoginLayout.setHorizontalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(332, 332, 332)
                .addComponent(panelLoginCard1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelLoginLayout.setVerticalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(panelLoginCard1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142))
        );

        tabbedAuthPage.addTab("tab2", panelLogin);

        panelAdmin.setBackground(new java.awt.Color(251, 245, 222));
        panelAdmin.setMaximumSize(new java.awt.Dimension(1000, 710));
        panelAdmin.setMinimumSize(new java.awt.Dimension(1000, 710));

        panelLoginCard.setBackground(new java.awt.Color(226, 71, 42));
        panelLoginCard.setMaximumSize(new java.awt.Dimension(361, 426));
        panelLoginCard.setMinimumSize(new java.awt.Dimension(361, 426));
        panelLoginCard.setName(""); // NOI18N

        textFieldPassword.setBackground(new java.awt.Color(255, 255, 255));
        textFieldPassword.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textFieldPassword.setForeground(new java.awt.Color(38, 50, 56));
        textFieldPassword.setText("Enter password");
        textFieldPassword.setPreferredSize(new java.awt.Dimension(297, 37));
        textFieldPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textFieldPasswordMouseClicked(evt);
            }
        });

        labelUserSignUp.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelUserSignUp.setForeground(new java.awt.Color(251, 245, 222));
        labelUserSignUp.setText("/Sign Up");
        labelUserSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelUserSignUpMouseClicked(evt);
            }
        });

        labelWelcome.setBackground(new java.awt.Color(251, 245, 222));
        labelWelcome.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        labelWelcome.setForeground(new java.awt.Color(38, 50, 56));
        labelWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelWelcome.setText("Admin");
        labelWelcome.setPreferredSize(new java.awt.Dimension(130, 58));

        labelUsername.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelUsername.setForeground(new java.awt.Color(38, 50, 56));
        labelUsername.setText("Username");
        labelUsername.setPreferredSize(new java.awt.Dimension(68, 17));

        labelPassword.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelPassword.setForeground(new java.awt.Color(38, 50, 56));
        labelPassword.setText("Password");
        labelPassword.setPreferredSize(new java.awt.Dimension(68, 17));

        labelUserLogin.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelUserLogin.setForeground(new java.awt.Color(251, 245, 222));
        labelUserLogin.setText("User Login");
        labelUserLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelUserLoginMouseClicked(evt);
            }
        });

        labelOrGoBack.setForeground(new java.awt.Color(38, 50, 56));
        labelOrGoBack.setText("Or go back to");

        adminBackBtn.setText("Back");
        adminBackBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminBackBtnMouseClicked(evt);
            }
        });

        labelLoginButton.setBackground(new java.awt.Color(221, 221, 221));
        labelLoginButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelLoginButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLoginButton.setText("Login");

        panelLoginAdmin.setBackground(java.awt.Color.black);
        panelLoginAdmin.setForeground(java.awt.Color.black);
        panelLoginAdmin.setRoundBottomLeft(20);
        panelLoginAdmin.setRoundBottomRight(20);
        panelLoginAdmin.setRoundTopLeft(20);
        panelLoginAdmin.setRoundTopRight(20);

        labelLoginAdmin.setBackground(java.awt.Color.white);
        labelLoginAdmin.setForeground(java.awt.Color.white);
        labelLoginAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLoginAdmin.setText("Login");
        labelLoginAdmin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelLoginAdminLayout = new javax.swing.GroupLayout(panelLoginAdmin);
        panelLoginAdmin.setLayout(panelLoginAdminLayout);
        panelLoginAdminLayout.setHorizontalGroup(
            panelLoginAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelLoginAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
        );
        panelLoginAdminLayout.setVerticalGroup(
            panelLoginAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelLoginAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        textFieldUsername.setBackground(new java.awt.Color(255, 255, 255));
        textFieldUsername.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textFieldUsername.setForeground(new java.awt.Color(38, 50, 56));
        textFieldUsername.setText("Enter username");
        textFieldUsername.setAutoscrolls(false);
        textFieldUsername.setPreferredSize(new java.awt.Dimension(297, 37));
        textFieldUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textFieldUsernameMouseClicked(evt);
            }
        });
        textFieldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldUsernameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLoginCardLayout = new javax.swing.GroupLayout(panelLoginCard);
        panelLoginCard.setLayout(panelLoginCardLayout);
        panelLoginCardLayout.setHorizontalGroup(
            panelLoginCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginCardLayout.createSequentialGroup()
                .addGroup(panelLoginCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLoginCardLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(panelLoginCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelLoginCardLayout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(labelOrGoBack)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelUserLogin)
                                .addGap(0, 0, 0)
                                .addComponent(labelUserSignUp))
                            .addComponent(labelWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelLoginCardLayout.createSequentialGroup()
                                .addComponent(panelLoginAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(textFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelLoginCardLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(adminBackBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLoginCardLayout.setVerticalGroup(
            panelLoginCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginCardLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(adminBackBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLoginCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLoginCardLayout.createSequentialGroup()
                        .addComponent(labelWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(textFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(panelLoginAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelLoginCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelOrGoBack)
                            .addComponent(labelUserLogin)
                            .addComponent(labelUserSignUp))
                        .addGap(71, 71, 71))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLoginCardLayout.createSequentialGroup()
                        .addComponent(labelLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88))))
        );

        javax.swing.GroupLayout panelAdminLayout = new javax.swing.GroupLayout(panelAdmin);
        panelAdmin.setLayout(panelAdminLayout);
        panelAdminLayout.setHorizontalGroup(
            panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminLayout.createSequentialGroup()
                .addGap(332, 332, 332)
                .addComponent(panelLoginCard, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(432, Short.MAX_VALUE))
        );
        panelAdminLayout.setVerticalGroup(
            panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminLayout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(panelLoginCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        tabbedAuthPage.addTab("tab1", panelAdmin);

        jPanel1.add(tabbedAuthPage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -34, -1, 830));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1096, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1096, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 796, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void labelAdmin1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAdmin1MouseClicked
        tabbedAuthPage.setSelectedIndex(2);
    }//GEN-LAST:event_labelAdmin1MouseClicked

    private void textFieldUsername2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldUsername2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldUsername2ActionPerformed

    private void labelLogin1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLogin1MouseClicked
        tabbedAuthPage.setSelectedIndex(1);
    }//GEN-LAST:event_labelLogin1MouseClicked

    private void textFieldConfirmPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldConfirmPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldConfirmPasswordActionPerformed

    private void textFieldUsername1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldUsername1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldUsername1ActionPerformed

    private void labelSignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelSignUpMouseClicked
        tabbedAuthPage.setSelectedIndex(0);
    }//GEN-LAST:event_labelSignUpMouseClicked

    private void labelAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelAdminMouseClicked
        tabbedAuthPage.setSelectedIndex(2);
    }//GEN-LAST:event_labelAdminMouseClicked

    private void textFieldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldUsernameActionPerformed

    private void labelUserSignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelUserSignUpMouseClicked
        tabbedAuthPage.setSelectedIndex(0);
    }//GEN-LAST:event_labelUserSignUpMouseClicked

    private void labelUserLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelUserLoginMouseClicked
        tabbedAuthPage.setSelectedIndex(1);
    }//GEN-LAST:event_labelUserLoginMouseClicked

    private void signUpBackBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signUpBackBtnMouseClicked
        pageController.goToPreviousPage();
        tabbedAuthPage.setSelectedIndex(1);
    }//GEN-LAST:event_signUpBackBtnMouseClicked

    private void adminBackBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminBackBtnMouseClicked
        pageController.goToPreviousPage();
        tabbedAuthPage.setSelectedIndex(1);
    }//GEN-LAST:event_adminBackBtnMouseClicked

    private void loginBackBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginBackBtnMouseClicked
        pageController.goToPreviousPage();
        tabbedAuthPage.setSelectedIndex(1);
    }//GEN-LAST:event_loginBackBtnMouseClicked

    private void textFieldUsername2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textFieldUsername2MouseClicked
        textFieldUsername2.setText("");
    }//GEN-LAST:event_textFieldUsername2MouseClicked

    private void textFieldUsername2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldUsername2FocusGained

    }//GEN-LAST:event_textFieldUsername2FocusGained

    private void textFieldUsername2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldUsername2FocusLost

    }//GEN-LAST:event_textFieldUsername2FocusLost

    private void textFieldPassword2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textFieldPassword2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldPassword2MouseClicked

    private void textFieldPassword2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textFieldPassword2MouseEntered
        textFieldPassword2.setText("");
    }//GEN-LAST:event_textFieldPassword2MouseEntered

    private void textFieldConfirmPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textFieldConfirmPasswordMouseClicked
        textFieldConfirmPassword.setText("");
    }//GEN-LAST:event_textFieldConfirmPasswordMouseClicked

    private void textFieldUsername1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textFieldUsername1MouseClicked
        textFieldUsername1.setText("");
    }//GEN-LAST:event_textFieldUsername1MouseClicked

    private void textFieldPassword1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textFieldPassword1MouseClicked
        textFieldPassword1.setText("");
    }//GEN-LAST:event_textFieldPassword1MouseClicked

    private void textFieldUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textFieldUsernameMouseClicked
        textFieldUsername.setText("");
    }//GEN-LAST:event_textFieldUsernameMouseClicked

    private void textFieldPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textFieldPasswordMouseClicked
        textFieldUsername.setText("");
    }//GEN-LAST:event_textFieldPasswordMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminBackBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelAdmin;
    private javax.swing.JLabel labelAdmin1;
    private javax.swing.JLabel labelAlreadyHave;
    private javax.swing.JLabel labelDontHave;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelLogin1;
    private javax.swing.JLabel labelLoginAdmin;
    private javax.swing.JLabel labelLoginAdmin1;
    private javax.swing.JLabel labelLoginAdmin3;
    private javax.swing.JLabel labelLoginButton;
    private javax.swing.JLabel labelOrGoBack;
    private javax.swing.JLabel labelOrLoginAs;
    private javax.swing.JLabel labelOrLoginAs1;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelPassword1;
    private javax.swing.JLabel labelPassword2;
    private javax.swing.JLabel labelSignUp;
    private javax.swing.JLabel labelSignUp1;
    private javax.swing.JLabel labelUserLogin;
    private javax.swing.JLabel labelUserSignUp;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JLabel labelUsername1;
    private javax.swing.JLabel labelUsername2;
    private javax.swing.JLabel labelWelcome;
    private javax.swing.JButton loginBackBtn;
    private javax.swing.JPanel panelAdmin;
    private javax.swing.JPanel panelLogin;
    private com.mycompany.thepetproject.swing.components.PanelRound panelLoginAdmin;
    private javax.swing.JPanel panelLoginCard;
    private javax.swing.JPanel panelLoginCard1;
    private com.mycompany.thepetproject.swing.components.PanelRound panelRound1;
    private com.mycompany.thepetproject.swing.components.PanelRound panelRound2;
    private javax.swing.JPanel panelSignUp;
    private javax.swing.JPanel panelSignUpCard;
    private javax.swing.JButton signUpBackBtn;
    private javax.swing.JTabbedPane tabbedAuthPage;
    private javax.swing.JTextField textFieldConfirmPassword;
    private javax.swing.JTextField textFieldPassword;
    private javax.swing.JTextField textFieldPassword1;
    private javax.swing.JTextField textFieldPassword2;
    private javax.swing.JTextField textFieldUsername;
    private javax.swing.JTextField textFieldUsername1;
    private javax.swing.JTextField textFieldUsername2;
    // End of variables declaration//GEN-END:variables
}
