/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.thepetproject.swing.pages;


import javax.swing.JOptionPane;

import com.mycompany.thepetproject.utils.auth.SessionManager;
import com.mycompany.thepetproject.utils.auth.SessionRole;
import com.mycompany.thepetproject.utils.auth.strategies.AdminAuthentication;
import com.mycompany.thepetproject.utils.auth.strategies.UserAuthentication;
import com.mycompany.thepetproject.utils.pages.PageBlueprint;
import com.mycompany.thepetproject.utils.pages.PageController;

/**
 *
 * @author deynklarys
 */
public class AuthPanel extends PageBlueprint {
    private PageController pageController;
    private SessionManager sessionManager;

    /**
     * Creates new form AuthPanel
     */
    public AuthPanel() {
        initComponents();
        this.pageController = PageController.getInstance();
        this.sessionManager = SessionManager.getInstance();    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAdmin = new javax.swing.JPanel();
        panelLoginCard = new javax.swing.JPanel();
        labelWelcome = new javax.swing.JLabel();
        labelUsername = new javax.swing.JLabel();
        labelPassword = new javax.swing.JLabel();
        labelLoginButton = new javax.swing.JLabel();
        panelLoginAdmin = new com.mycompany.thepetproject.swing.components.PanelRound();
        labelLoginAdmin = new javax.swing.JLabel();
        textFieldUsername = new javax.swing.JTextField();
        passwordField2 = new javax.swing.JPasswordField();
        panelRound3 = new com.mycompany.thepetproject.swing.components.PanelRound();
        label1 = new java.awt.Label();

        setMaximumSize(new java.awt.Dimension(1000, 710));
        setMinimumSize(new java.awt.Dimension(1000, 710));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelAdmin.setBackground(new java.awt.Color(251, 245, 222));
        panelAdmin.setMaximumSize(new java.awt.Dimension(1000, 710));
        panelAdmin.setMinimumSize(new java.awt.Dimension(1000, 710));

        panelLoginCard.setBackground(new java.awt.Color(226, 71, 42));
        panelLoginCard.setMaximumSize(new java.awt.Dimension(361, 426));
        panelLoginCard.setMinimumSize(new java.awt.Dimension(361, 426));
        panelLoginCard.setName(""); // NOI18N

        labelWelcome.setBackground(new java.awt.Color(251, 245, 222));
        labelWelcome.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        labelWelcome.setForeground(new java.awt.Color(38, 50, 56));
        labelWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelWelcome.setText("Admin");
        labelWelcome.setPreferredSize(new java.awt.Dimension(130, 58));

        labelUsername.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelUsername.setForeground(new java.awt.Color(38, 50, 56));
        labelUsername.setText("Username");
        labelUsername.setPreferredSize(new java.awt.Dimension(68, 17));

        labelPassword.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelPassword.setForeground(new java.awt.Color(38, 50, 56));
        labelPassword.setText("Password");
        labelPassword.setPreferredSize(new java.awt.Dimension(68, 17));

        labelLoginButton.setBackground(new java.awt.Color(221, 221, 221));
        labelLoginButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelLoginButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLoginButton.setText("Login");

        panelLoginAdmin.setBackground(java.awt.Color.black);
        panelLoginAdmin.setRoundBottomLeft(20);
        panelLoginAdmin.setRoundBottomRight(20);
        panelLoginAdmin.setRoundTopLeft(20);
        panelLoginAdmin.setRoundTopRight(20);
        panelLoginAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelLoginAdminMouseClicked(evt);
            }
        });

        labelLoginAdmin.setBackground(java.awt.Color.white);
        labelLoginAdmin.setForeground(java.awt.Color.white);
        labelLoginAdmin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLoginAdmin.setText("Login");
        labelLoginAdmin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        labelLoginAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelLoginAdminMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelLoginAdminLayout = new javax.swing.GroupLayout(panelLoginAdmin);
        panelLoginAdmin.setLayout(panelLoginAdminLayout);
        panelLoginAdminLayout.setHorizontalGroup(
            panelLoginAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelLoginAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
        );
        panelLoginAdminLayout.setVerticalGroup(
            panelLoginAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelLoginAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        textFieldUsername.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        textFieldUsername.setForeground(new java.awt.Color(38, 50, 56));
        textFieldUsername.setText("Enter username");
        textFieldUsername.setAutoscrolls(false);
        textFieldUsername.setPreferredSize(new java.awt.Dimension(297, 37));
        textFieldUsername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldUsernameFocusGained(evt);
            }
        });
        textFieldUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldUsernameActionPerformed(evt);
            }
        });

        passwordField2.setText("password");
        passwordField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordField2FocusGained(evt);
            }
        });

        panelRound3.setBackground(java.awt.Color.black);
        panelRound3.setRoundBottomLeft(20);
        panelRound3.setRoundBottomRight(20);
        panelRound3.setRoundTopLeft(20);
        panelRound3.setRoundTopRight(20);
        panelRound3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelRound3MouseClicked(evt);
            }
        });

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setBackground(java.awt.Color.black);
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Back");
        label1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelRound3Layout = new javax.swing.GroupLayout(panelRound3);
        panelRound3.setLayout(panelRound3Layout);
        panelRound3Layout.setHorizontalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound3Layout.setVerticalGroup(
            panelRound3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelLoginCardLayout = new javax.swing.GroupLayout(panelLoginCard);
        panelLoginCard.setLayout(panelLoginCardLayout);
        panelLoginCardLayout.setHorizontalGroup(
            panelLoginCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginCardLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(panelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelLoginCardLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(panelLoginCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelLoginCardLayout.createSequentialGroup()
                        .addComponent(panelLoginAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(textFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        panelLoginCardLayout.setVerticalGroup(
            panelLoginCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginCardLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(panelRound3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLoginCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLoginCardLayout.createSequentialGroup()
                        .addComponent(labelWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(textFieldUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passwordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(panelLoginAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLoginCardLayout.createSequentialGroup()
                        .addComponent(labelLoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88))))
        );

        javax.swing.GroupLayout panelAdminLayout = new javax.swing.GroupLayout(panelAdmin);
        panelAdmin.setLayout(panelAdminLayout);
        panelAdminLayout.setHorizontalGroup(
            panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminLayout.createSequentialGroup()
                .addGap(332, 332, 332)
                .addComponent(panelLoginCard, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(332, Short.MAX_VALUE))
        );
        panelAdminLayout.setVerticalGroup(
            panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminLayout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(panelLoginCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(159, Short.MAX_VALUE))
        );

        add(panelAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void labelLoginAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelLoginAdminMouseClicked
        System.out.println("CLICK USER LOGIN");
        String usernameLogin = textFieldUsername.getText().trim();
        String passwordLogin = new String(passwordField2.getPassword());

        System.out.println("Username: " + usernameLogin);
        System.out.println("Password: " + passwordLogin);

        AdminAuthentication authentication = new AdminAuthentication();
        boolean isAuthenticated = sessionManager.authenticate(SessionRole.ADMIN, usernameLogin, passwordLogin, authentication);
        if (isAuthenticated) {
            pageController.changePage("AdminDashboard");
        } else {
            JOptionPane.showMessageDialog(this, "Invalid admin credentials", "Authentication Failed", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_labelLoginAdminMouseClicked

    private void panelLoginAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelLoginAdminMouseClicked
        System.out.println("CLICK ADMIN LOGIN");
        String usernameLogin = textFieldUsername.getText().trim();
        String passwordLogin = new String(passwordField2.getPassword());

        System.out.println("Username: " + usernameLogin);
        System.out.println("Password: " + passwordLogin);

        AdminAuthentication authentication = new AdminAuthentication();
        boolean isAuthenticated = sessionManager.authenticate(SessionRole.ADMIN, usernameLogin, passwordLogin, authentication);
        if (isAuthenticated) {
            pageController.changePage("AdminDashboard");
        } else {
            JOptionPane.showMessageDialog(this, "Invalid admin credentials", "Authentication Failed", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_panelLoginAdminMouseClicked

    private void textFieldUsernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldUsernameFocusGained
        textFieldUsername.setText("");
    }//GEN-LAST:event_textFieldUsernameFocusGained

    private void textFieldUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldUsernameActionPerformed

    private void passwordField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordField2FocusGained
        passwordField2.setText("");
    }//GEN-LAST:event_passwordField2FocusGained

    private void label1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label1MouseClicked
        pageController.goToPreviousPage();
    }//GEN-LAST:event_label1MouseClicked

    private void panelRound3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound3MouseClicked
        pageController.goToPreviousPage();
    }//GEN-LAST:event_panelRound3MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label label1;
    private javax.swing.JLabel labelLoginAdmin;
    private javax.swing.JLabel labelLoginButton;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JLabel labelWelcome;
    private javax.swing.JPanel panelAdmin;
    private com.mycompany.thepetproject.swing.components.PanelRound panelLoginAdmin;
    private javax.swing.JPanel panelLoginCard;
    private com.mycompany.thepetproject.swing.components.PanelRound panelRound3;
    private javax.swing.JPasswordField passwordField2;
    private javax.swing.JTextField textFieldUsername;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update() {
    }
}
