/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.thepetproject.swing.pages;

import com.mycompany.thepetproject.swing.pages.TestUserLogin;

/**
 *
 * @author lilac
 */
public class TestHome extends javax.swing.JFrame {

    /**
     * Creates new form TestHome
     */
    public TestHome() {
        initComponents();
        pagesTabbedPane.addTab("tab4", new TestUserLogin(pagesTabbedPane));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pagesTabbedPane = new javax.swing.JTabbedPane();
        home = new javax.swing.JPanel();
        HomeToViewPetsBtn = new javax.swing.JButton();
        HomeToUserLoginBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        petGallery = new javax.swing.JPanel();
        petGalleryToHomeBtn = new javax.swing.JButton();
        petGalleryToUserLoginBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        userLogin = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        home.setBackground(new java.awt.Color(255, 0, 0));

        HomeToViewPetsBtn.setText("View Pets");
        HomeToViewPetsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeToViewPetsBtnMouseClicked(evt);
            }
        });

        HomeToUserLoginBtn.setText("Login");
        HomeToUserLoginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeToUserLoginBtnMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel3.setText("Home");

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(home);
        home.setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(HomeToViewPetsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(HomeToUserLoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(274, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(431, 431, 431))
        );
        homeLayout.setVerticalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(80, 80, 80)
                .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HomeToViewPetsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HomeToUserLoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(269, 269, 269))
        );

        pagesTabbedPane.addTab("tab1", home);

        petGallery.setBackground(new java.awt.Color(51, 204, 0));

        petGalleryToHomeBtn.setText("Home");
        petGalleryToHomeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                petGalleryToHomeBtnMouseClicked(evt);
            }
        });

        petGalleryToUserLoginBtn.setText("Login");
        petGalleryToUserLoginBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                petGalleryToUserLoginBtnMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jLabel2.setText("Pet Gallery");

        javax.swing.GroupLayout petGalleryLayout = new javax.swing.GroupLayout(petGallery);
        petGallery.setLayout(petGalleryLayout);
        petGalleryLayout.setHorizontalGroup(
            petGalleryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(petGalleryLayout.createSequentialGroup()
                .addGroup(petGalleryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(petGalleryLayout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(petGalleryToHomeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(petGalleryToUserLoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(petGalleryLayout.createSequentialGroup()
                        .addGap(399, 399, 399)
                        .addComponent(jLabel2)))
                .addContainerGap(361, Short.MAX_VALUE))
        );
        petGalleryLayout.setVerticalGroup(
            petGalleryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(petGalleryLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(89, 89, 89)
                .addGroup(petGalleryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(petGalleryToHomeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(petGalleryToUserLoginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(306, 306, 306))
        );

        pagesTabbedPane.addTab("tab2", petGallery);

        userLogin.setBackground(new java.awt.Color(0, 0, 204));

        javax.swing.GroupLayout userLoginLayout = new javax.swing.GroupLayout(userLogin);
        userLogin.setLayout(userLoginLayout);
        userLoginLayout.setHorizontalGroup(
            userLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        userLoginLayout.setVerticalGroup(
            userLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 715, Short.MAX_VALUE)
        );

        pagesTabbedPane.addTab("tab3", userLogin);

        getContentPane().add(pagesTabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, -40, 1000, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeToViewPetsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeToViewPetsBtnMouseClicked
        // TODO add your handling code here:
        pagesTabbedPane.setSelectedIndex(1);
    }//GEN-LAST:event_HomeToViewPetsBtnMouseClicked

    private void HomeToUserLoginBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeToUserLoginBtnMouseClicked
        // TODO add your handling code here:
        pagesTabbedPane.setSelectedIndex(3);
    }//GEN-LAST:event_HomeToUserLoginBtnMouseClicked

    private void petGalleryToHomeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_petGalleryToHomeBtnMouseClicked
        // TODO add your handling code here:
        pagesTabbedPane.setSelectedIndex(0);
    }//GEN-LAST:event_petGalleryToHomeBtnMouseClicked

    private void petGalleryToUserLoginBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_petGalleryToUserLoginBtnMouseClicked
        // TODO add your handling code here:
        pagesTabbedPane.setSelectedIndex(3);
    }//GEN-LAST:event_petGalleryToUserLoginBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HomeToUserLoginBtn;
    private javax.swing.JButton HomeToViewPetsBtn;
    private javax.swing.JPanel home;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTabbedPane pagesTabbedPane;
    private javax.swing.JPanel petGallery;
    private javax.swing.JButton petGalleryToHomeBtn;
    private javax.swing.JButton petGalleryToUserLoginBtn;
    private javax.swing.JPanel userLogin;
    // End of variables declaration//GEN-END:variables
}
