/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.thepetproject.frames;

/**
 *
 * @author deynklarys
 */
public class PetCard extends javax.swing.JPanel {

    /**
     * Creates new form petCard
     */
    public PetCard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPetCard1 = new javax.swing.JPanel();
        labelPetName1 = new javax.swing.JLabel();
        labelSex1 = new javax.swing.JLabel();
        labelAge1 = new javax.swing.JLabel();
        labelImage = new javax.swing.JLabel();
        labelSetAge1 = new javax.swing.JLabel();
        labelSetSex1 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        panelPetCard1.setBackground(new java.awt.Color(248, 208, 70));
        panelPetCard1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        labelPetName1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        labelPetName1.setText("petName");

        labelSex1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        labelSex1.setText("Sex: ");
        labelSex1.setPreferredSize(new java.awt.Dimension(30, 15));

        labelAge1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        labelAge1.setText("Age:");
        labelAge1.setPreferredSize(new java.awt.Dimension(30, 15));

        labelImage.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        labelImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/thepetproject/frames/dog.png"))); // NOI18N

        labelSetAge1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        labelSetAge1.setText("2 years");

        labelSetSex1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        labelSetSex1.setText("female");
        labelSetSex1.setPreferredSize(new java.awt.Dimension(40, 15));

        javax.swing.GroupLayout panelPetCard1Layout = new javax.swing.GroupLayout(panelPetCard1);
        panelPetCard1.setLayout(panelPetCard1Layout);
        panelPetCard1Layout.setHorizontalGroup(
            panelPetCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPetCard1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panelPetCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPetCard1Layout.createSequentialGroup()
                        .addComponent(labelImage, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                        .addGap(12, 12, 12))
                    .addGroup(panelPetCard1Layout.createSequentialGroup()
                        .addGroup(panelPetCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelPetCard1Layout.createSequentialGroup()
                                .addComponent(labelSex1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelSetSex1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(labelPetName1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(panelPetCard1Layout.createSequentialGroup()
                                .addComponent(labelAge1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelSetAge1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelPetCard1Layout.setVerticalGroup(
            panelPetCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPetCard1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(labelImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelPetName1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPetCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAge1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSetAge1))
                .addGap(2, 2, 2)
                .addGroup(panelPetCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSex1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSetSex1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(panelPetCard1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelAge1;
    private javax.swing.JLabel labelImage;
    private javax.swing.JLabel labelPetName1;
    private javax.swing.JLabel labelSetAge1;
    private javax.swing.JLabel labelSetSex1;
    private javax.swing.JLabel labelSex1;
    private javax.swing.JPanel panelPetCard1;
    // End of variables declaration//GEN-END:variables
}
