/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.thepetproject.frames;

/**
 *
 * @author lilac
 */
public class Sandbox extends javax.swing.JFrame {

    /**
     * Creates new form BrowsePets
     */
    public Sandbox() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelPetAdoption = new javax.swing.JLabel();
        labelImageCat = new javax.swing.JLabel();
        labelCats = new javax.swing.JLabel();
        labelImageDog = new javax.swing.JLabel();
        labelDogs = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        panelPetCard1 = new javax.swing.JPanel();
        labelPetName1 = new javax.swing.JLabel();
        labelSex1 = new javax.swing.JLabel();
        labelAge1 = new javax.swing.JLabel();
        labelImage = new javax.swing.JLabel();
        labelSetAge1 = new javax.swing.JLabel();
        labelSetSex1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        buttonLogIn1 = new javax.swing.JButton();
        labelHome1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(226, 70, 43));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        labelPetAdoption.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        labelPetAdoption.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPetAdoption.setText("Pets For Adoption");

        labelImageCat.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        labelImageCat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelImageCat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/thepetproject/frames/cat.png"))); // NOI18N

        labelCats.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        labelCats.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCats.setText("Cats");

        labelImageDog.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        labelImageDog.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelImageDog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/thepetproject/frames/dog.png"))); // NOI18N

        labelDogs.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        labelDogs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelDogs.setText("Dogs");

        panelPetCard1.setBackground(new java.awt.Color(248, 208, 70));
        panelPetCard1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        labelPetName1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        labelPetName1.setText("petName");

        labelSex1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        labelSex1.setText("Sex: ");

        labelAge1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        labelAge1.setText("Age:");

        labelImage.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        labelImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/thepetproject/frames/dog.png"))); // NOI18N

        labelSetAge1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        labelSetAge1.setText("yrs old");

        labelSetSex1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        labelSetSex1.setText("female");

        javax.swing.GroupLayout panelPetCard1Layout = new javax.swing.GroupLayout(panelPetCard1);
        panelPetCard1.setLayout(panelPetCard1Layout);
        panelPetCard1Layout.setHorizontalGroup(
            panelPetCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPetCard1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPetCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPetCard1Layout.createSequentialGroup()
                        .addGroup(panelPetCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPetCard1Layout.createSequentialGroup()
                                .addComponent(labelSex1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelSetSex1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(panelPetCard1Layout.createSequentialGroup()
                                .addGroup(panelPetCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelImage, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelPetCard1Layout.createSequentialGroup()
                                        .addComponent(labelAge1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelSetAge1)))
                                .addGap(0, 6, Short.MAX_VALUE)))
                        .addGap(6, 6, 6))
                    .addGroup(panelPetCard1Layout.createSequentialGroup()
                        .addComponent(labelPetName1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelPetCard1Layout.setVerticalGroup(
            panelPetCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPetCard1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(labelImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelPetName1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPetCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAge1)
                    .addComponent(labelSetAge1))
                .addGap(10, 10, 10)
                .addGroup(panelPetCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSex1)
                    .addComponent(labelSetSex1))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPetCard1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(568, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPetCard1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(329, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelPetAdoption)
                .addGap(321, 321, 321))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(425, 425, 425)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelImageDog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelDogs, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelCats, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelImageCat, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(labelPetAdoption, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelImageDog, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(labelDogs))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelImageCat, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(labelCats)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel3.setBackground(new java.awt.Color(204, 255, 51));

        buttonLogIn1.setBackground(new java.awt.Color(226, 70, 43));
        buttonLogIn1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        buttonLogIn1.setForeground(new java.awt.Color(255, 255, 255));
        buttonLogIn1.setText("Log In");
        buttonLogIn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonLogIn1MouseClicked(evt);
            }
        });
        buttonLogIn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogIn1ActionPerformed(evt);
            }
        });

        labelHome1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        labelHome1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHome1.setText("Home");
        labelHome1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelHome1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(154, Short.MAX_VALUE)
                .addComponent(buttonLogIn1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelHome1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(644, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonLogIn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelHome1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLogIn1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLogIn1MouseClicked
        UserLogin login = new UserLogin();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonLogIn1MouseClicked

    private void buttonLogIn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogIn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonLogIn1ActionPerformed

    private void labelHome1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelHome1MouseClicked
        Home homePage = new Home();
        homePage.setVisible(true);
        dispose();
    }//GEN-LAST:event_labelHome1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PetGallery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PetGallery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PetGallery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PetGallery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PetGallery().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLogIn1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel labelAge1;
    private javax.swing.JLabel labelAge2;
    private javax.swing.JLabel labelAge3;
    private javax.swing.JLabel labelAge4;
    private javax.swing.JLabel labelCats;
    private javax.swing.JLabel labelDogs;
    private javax.swing.JLabel labelHome1;
    private javax.swing.JLabel labelImage;
    private javax.swing.JLabel labelImage1;
    private javax.swing.JLabel labelImage2;
    private javax.swing.JLabel labelImage3;
    private javax.swing.JLabel labelImageCat;
    private javax.swing.JLabel labelImageDog;
    private javax.swing.JLabel labelPetAdoption;
    private javax.swing.JLabel labelPetName1;
    private javax.swing.JLabel labelPetName2;
    private javax.swing.JLabel labelPetName3;
    private javax.swing.JLabel labelPetName4;
    private javax.swing.JLabel labelSetAge1;
    private javax.swing.JLabel labelSetAge2;
    private javax.swing.JLabel labelSetAge3;
    private javax.swing.JLabel labelSetAge4;
    private javax.swing.JLabel labelSetSex1;
    private javax.swing.JLabel labelSetSex2;
    private javax.swing.JLabel labelSetSex3;
    private javax.swing.JLabel labelSetSex4;
    private javax.swing.JLabel labelSex1;
    private javax.swing.JLabel labelSex2;
    private javax.swing.JLabel labelSex3;
    private javax.swing.JLabel labelSex4;
    private javax.swing.JPanel panelPetCard1;
    private javax.swing.JPanel panelPetCard2;
    private javax.swing.JPanel panelPetCard3;
    private javax.swing.JPanel panelPetCard4;
    // End of variables declaration//GEN-END:variables
}
