/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.thepetproject.swing.components;

import com.mycompany.thepetproject.main.PetSex;
import com.mycompany.thepetproject.main.PetType;
import com.mycompany.thepetproject.swing.components.PetModal;

/**
 *
 * @author deynklarys
 */

/**
 * name.setFont(fontBold20f);
 * labelAge.setFont(fontBold20f);
 * labelSex.setFont(fontBold14f);
 * age.setFont(fontPlain14f);
 * sex.setFont(fontPlain14f);
 */
public class PetCard extends javax.swing.JPanel {

    private String id;
    private String name;
    private PetSex sex;
    private PetType type;
    private int age;
    private String description;
    
    /**
     * Creates new form PetCard
     */
    public PetCard(String id, String name, PetSex sex, PetType type, int age, String description) {
        initComponents();
        
        this.id = id;
        this.name = name;
        this.sex = sex;
        this.type = type;
        this.age = age;
        this.description = description;
        
        this.nameLabel.setText(name);
        this.ageLabel.setText(String.valueOf(age));
        this.sexLabel.setText(sex.toString());
        this.id = id;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelRound1 = new com.mycompany.thepetproject.swing.components.PanelRound();
        image = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        labelAge = new javax.swing.JLabel();
        labelSex = new javax.swing.JLabel();
        ageLabel = new javax.swing.JLabel();
        sexLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(251, 244, 191));
        setMaximumSize(new java.awt.Dimension(150, 230));
        setMinimumSize(new java.awt.Dimension(150, 230));
        setPreferredSize(new java.awt.Dimension(150, 230));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setOpaque(false);
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 230));

        panelRound1.setBackground(new java.awt.Color(248, 208, 70));
        panelRound1.setMaximumSize(new java.awt.Dimension(150, 230));
        panelRound1.setMinimumSize(new java.awt.Dimension(150, 230));
        panelRound1.setPreferredSize(new java.awt.Dimension(150, 130));

        image.setForeground(new java.awt.Color(38, 50, 56));
        image.setText("image");
        image.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(38, 50, 56), 1, true));

        nameLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(38, 50, 56));
        nameLabel.setText("name");

        labelAge.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelAge.setForeground(new java.awt.Color(38, 50, 56));
        labelAge.setText("Age:");

        labelSex.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelSex.setForeground(new java.awt.Color(38, 50, 56));
        labelSex.setText("Sex:");

        ageLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ageLabel.setForeground(new java.awt.Color(38, 50, 56));
        ageLabel.setText("age");

        sexLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        sexLabel.setForeground(new java.awt.Color(38, 50, 56));
        sexLabel.setText("sex");

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRound1Layout.createSequentialGroup()
                                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 46, Short.MAX_VALUE))
                            .addGroup(panelRound1Layout.createSequentialGroup()
                                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(labelSex, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelAge, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ageLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(sexLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addComponent(image, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(123, 123, 123)
                .addComponent(nameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAge)
                    .addComponent(ageLabel))
                .addGap(0, 0, 0)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSex)
                    .addComponent(sexLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(panelRound1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 230));
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        System.out.println("Card clicked!");
//        String id, String name, PetSex sex, PetType type, int age, String description
        PetModal modal = new PetModal(id, name, sex, type, age, description);
        modal.setVisible(true);
        modal.pack();
        modal.setLocationRelativeTo(null);
        modal.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jPanel1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ageLabel;
    private javax.swing.JLabel image;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelAge;
    private javax.swing.JLabel labelSex;
    private javax.swing.JLabel nameLabel;
    private com.mycompany.thepetproject.swing.components.PanelRound panelRound1;
    private javax.swing.JLabel sexLabel;
    // End of variables declaration//GEN-END:variables
}
